### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by lectrician1** [siddharthvp/mwn#21]
None of the links for this package's documentation work on the [NPM page](https://www.npmjs.com/package/mwn). Is there any link for documentation that works?

**Comment by siddharthvp** [comment]
They are working on the GitHub page. I just did a new patch version release so that the links now work on NPM as well. 

The docs are basically the README and the [API docs](https://tools-static.wmflabs.org/mwn/docs/classes/mwn.html). Overall, documentation is a bit lacking in this project because this a single package with too many features to describe in a single README page. Let me know if there's anything specific that you'd want better documented.

**Comment by siddharthvp** [comment]
> Overall, documentation is a bit lacking in this project

This should be resolved now as the documentation website https://mwn.toolforge.org/ has been set up.
