### ISSUE TITLE
Add middleware for handling login session expiry

### ISSUE THREAD

**Issue by ChlodAlejandro** [siddharthvp/mwn#38]
Currently, mwn does not attempt to intercept expired sessions to perform re-logins if the session expired (usually after being logged in for extended periods). Unfortunately, this bleeds into request functions such as `massQuery`, and ends up causing a chain of errors down the line due to the unexpected input (a login error instead of the expected response).

For reference, here is the data returned by one of the `massQuery` responses:
```json
{
    "code": "mwn_failedlogin",
    "info": "Failed: Unable to continue login. Your session most likely timed out.",
    "response": {
        "login": {
            "result": "Failed",
            "reason": "Unable to continue login. Your session most likely timed out."
        }
    }
}
```
Subsequent errors after this one return the following:
```json
{
    "code": "mwn_failedlogin",
    "info": "Login failed",
    "response": {
        "login": {
            "result": "WrongToken"
        }
    }
}
```

It would be great to have mwn automatically check and determine if the session has expired and seamlessly re-login with a new login token. This removes the need to pile on additional code on every single request in order to trigger a re-login (and re-try of the request).

**Comment by siddharthvp** [comment]
I didn't get how exactly this arises – I haven't ever encountered this. In case of loss of session cookies (user getting logged out), the use of assert=user or assert=bot would cause all later API calls to fail with assertuserfailed/assertbotfailed – which [mwn does handle](https://github.com/siddharthvp/mwn/blob/f7007b092f4dae69a88083f990d08ebb578b1527/src/core.ts#L310) by logging in again.

This sounds like a failure in login due to a stale login token, but [login always fetches a new token](https://github.com/siddharthvp/mwn/blob/f7007b092f4dae69a88083f990d08ebb578b1527/src/bot.ts#L547).

**Comment by siddharthvp** [comment]
A very belated note - the issue you were running into was most likely #83, which has been fixed now.
